version: "3.9"

services:
  web:
    build: .
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    volumes:
      - ./app:/code/app
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --reload
